### ISSUE TITLE
waiting for code

### ISSUE THREAD

**Issue by yican-huang** [xzz777/SCTNet#1]

**Comment by MrWhiteHomeman** [comment]
wait for code

**Comment by xzz777** [comment]
Thanks for your patience and sorry for not updating the code on time.
I've been quite busy recently, so the plan to update the code has been temporarily delayed. 
I'll do my best to release the code as soon as possible. According to our current plan, we will release our code and model on next weekend. 
Thanks for your attention to our work! If you have any other questions, feel free to reach out.

**Comment by xzz777** [comment]
Code and models have been released
